version: "3"

services:
  meilisearch:
    image: getmeili/meilisearch:v0.21.0rc3
    container_name: meilisearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 7700:7700
