version: "3"

services:
  typesense:
    image: typesense/typesense:0.21.0
    container_name: typesense
    volumes:
      - ./.data/typesense/data:/data
    environment:
      - "TYPESENSE_DATA_DIR=/data"
      - "TYPESENSE_API_KEY=TEST"
      - "TYPESENSE_THREAD_POOL_SIZE=96"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 8108:8108
